import { useState } from "react";
import {
  ResizableHandle,
  ResizablePanel,
  ResizablePanelGroup,
} from "@/components/ui/resizable";
import { ChatPanel } from "@/components/agent/ChatPanel";
import { CodePanel } from "@/components/agent/CodePanel";
import { PreviewPanel } from "@/components/agent/PreviewPanel";

type ComponentNode = {
  type: string;
  props?: Record<string, any>;
  children?: (ComponentNode | string)[];
};

type UIPlan = {
  layout: string;
  modificationType: "create" | "update";
  components: ComponentNode[];
};

type GenerationResult = {
  plan: UIPlan | null;
  code: string;
  explanation: string;
  timestamp: number;
};

const INITIAL_CODE = `// Ready to generate UI...`;

export default function Home() {
  const [isGenerating, setIsGenerating] = useState(false);
  const [result, setResult] = useState<GenerationResult | null>(null);

  const handleGenerate = async (prompt: string) => {
    setIsGenerating(true);

    try {
      console.log("🧠 Sending prompt:", prompt);

      const response = await fetch("/api/plan", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt }),
      });

      if (!response.ok) {
        throw new Error("Backend returned non-200 response");
      }

      const plan: UIPlan = await response.json();

      console.log("🔥 PLAN FROM BACKEND:", plan);

      setResult({
        plan,
        code: JSON.stringify(plan, null, 2),
        explanation: "Generated by AI backend.",
        timestamp: Date.now(),
      });

    } catch (error) {
      console.error("❌ Generation failed:", error);

      setResult({
        plan: null,
        code: "// Error generating UI",
        explanation: "Backend or AI error occurred.",
        timestamp: Date.now(),
      });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleReset = () => {
    setResult(null);
  };

  return (
    <div className="h-screen w-full bg-background overflow-hidden flex flex-col">
      <ResizablePanelGroup direction="horizontal" className="flex-1">
        
        {/* LEFT PANEL */}
        <ResizablePanel defaultSize={25} minSize={20} maxSize={40}>
          <ChatPanel
            onGenerate={handleGenerate}
            onReset={handleReset}
            explanation={result?.explanation || ""}
            isGenerating={isGenerating}
          />
        </ResizablePanel>

        <ResizableHandle withHandle />

        {/* RIGHT PANEL */}
        <ResizablePanel defaultSize={75}>
          <ResizablePanelGroup direction="horizontal">

            {/* CODE PANEL */}
            <ResizablePanel defaultSize={40} minSize={20}>
              <CodePanel code={result?.code || INITIAL_CODE} />
            </ResizablePanel>

            <ResizableHandle withHandle />

            {/* PREVIEW PANEL */}
            <ResizablePanel defaultSize={60} minSize={30}>
              <PreviewPanel plan={result?.plan || null} />
            </ResizablePanel>

          </ResizablePanelGroup>
        </ResizablePanel>
      </ResizablePanelGroup>
    </div>
  );
}
